# Generated by Django 2.0 on 2018-09-29 10:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('rating', models.IntegerField(default=0)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500)),
                ('post', models.TextField(blank=True)),
                ('post_para_2', models.TextField(blank=True)),
                ('post_para_3', models.TextField(blank=True)),
                ('captions', models.TextField(blank=True)),
                ('captions_para_2', models.TextField(blank=True)),
                ('captions_para_3', models.TextField(blank=True)),
                ('quote', models.CharField(blank=True, max_length=200)),
                ('quote_by', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='post_image/%Y/%m/%d/')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('related_post_1', models.CharField(blank=True, max_length=100)),
                ('related_link_1', models.CharField(blank=True, max_length=100)),
                ('related_post_2', models.CharField(blank=True, max_length=100)),
                ('related_link_2', models.CharField(blank=True, max_length=100)),
                ('related_post_3', models.CharField(blank=True, max_length=100)),
                ('related_link_3', models.CharField(blank=True, max_length=100)),
                ('rating', models.IntegerField(default=0)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Category')),
            ],
        ),
    ]
